# Generated by Django 5.1.7 on 2025-05-08 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='onboarding_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('profile_completed', 'Profile Completed'), ('subscription_completed', 'Subscription Completed'), ('campaign_created', 'Campaign Created'), ('complete', 'Complete')], default='incomplete', max_length=50),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('payfast_token', models.CharField(blank=True, max_length=255, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.business')),
            ],
        ),
    ]
